const GET_DOGS = "GET_DOGS";
const GET_DOGS_BY_NAME = "GET_DOGS_BY_NAME";
const GET_DOGS_BY_ID = "GET_DOGS_BY_ID";
const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
const CREATE_DOG = "CREATE_DOG";
const FILTER = "FILTER";
const ORDER = "ORDER";

export {
  GET_DOGS,
  GET_DOGS_BY_NAME,
  GET_DOGS_BY_ID,
  GET_TEMPERAMENTS,
  CREATE_DOG,
  FILTER,
  ORDER,
};
